name: 🐞 Rapport de Bug (mais avec un formulaire)
description: Rapporter un problème / un bug
title: "[BUG] <titre>"
labels: [Bug]
body:
- type: checkboxes
  attributes:
    label: Existe t il déjà une issue pour ce bug?
    description: Merci de chercher si ce bug n'a pas déjà été rapporté.
    options:
    - label: J'ai cherché si ce bug avait déjà été rapporté
      required: true
- type: textarea
  attributes:
    label: Comportement actuel
    description: Description rapide du problème rencontré.
  validations:
    required: false
- type: textarea
  attributes:
    label: Comportement attendu
    description: Description rapide de ce qui est attendu.
  validations:
    required: false
- type: textarea
  attributes:
    label: Reproduction du problème
    description: Steps to reproduce the behaviorEtapes pour reproduire le problème.
    placeholder: |
      1. Avec la configuration ...
      2. Dans cet environnement...
      3. Exécutez '...'
      4. L'erreur suivante est affichée...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environnement
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS: 
        - Node: 
        - npm: 
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Autre chose?
    description: |
      Liens? Références? N'importe quoi pour nous donner plus d'informations pour résoudre ce bug!
      
      Astuce: Vous pouvez attacher des images ou des fichiers logs en cliquant dans cette zone pour l'activer, et ensuite glisser - déposer des fichiers à l'intérieur.
  validations:
    required: false
